# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/ruby_parser/all/ruby_parser.rbi
#
# ruby_parser-3.22.0

class RubyParser
  def current; end
  def current=(arg0); end
  def parse(s, f = nil, t = nil); end
  def process(s, f = nil, t = nil); end
  def reset; end
  def self.for_current_ruby; end
  def self.latest; end
end
class RubyParser::Parser < Racc::Parser
  def self.inherited(x); end
  def self.version; end
  def self.version=(v); end
  include RubyParserStuff
end
class RubyParser::SyntaxError < RuntimeError
end
class RubyParser::V34 < Ruby34Parser
end
class RubyParser::V33 < Ruby33Parser
end
class RubyParser::V32 < Ruby32Parser
end
class RubyParser::V31 < Ruby31Parser
end
class RubyParser::V30 < Ruby30Parser
end
class RubyParser::V27 < Ruby27Parser
end
class RubyParser::V26 < Ruby26Parser
end
class RubyParser::V25 < Ruby25Parser
end
class RubyParser::V24 < Ruby24Parser
end
class RubyParser::V23 < Ruby23Parser
end
class RubyParser::V22 < Ruby22Parser
end
class RubyParser::V21 < Ruby21Parser
end
class RubyParser::V20 < Ruby20Parser
end
