# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/sexp_processor/all/sexp_processor.rbi
#
# sexp_processor-4.17.5

class SexpProcessor
  def assert_empty(meth, exp, exp_orig); end
  def assert_type(list, typ); end
  def auto_shift_type; end
  def auto_shift_type=(arg0); end
  def context; end
  def debug; end
  def debug=(arg0); end
  def default_method; end
  def default_method=(arg0); end
  def env; end
  def error_handler(type, exp = nil); end
  def expected; end
  def expected=(arg0); end
  def in_context(type); end
  def initialize; end
  def on_error_in(node_type, &block); end
  def process(exp); end
  def process_dummy(exp); end
  def require_empty; end
  def require_empty=(arg0); end
  def rewrite(exp); end
  def scope(&block); end
  def self.expand_dirs_to_files(*dirs); end
  def self.processors; end
  def self.rewriters; end
  def strict; end
  def strict=(arg0); end
  def unsupported; end
  def unsupported=(arg0); end
  def warn_on_default; end
  def warn_on_default=(arg0); end
end
class SexpProcessor::Environment
  def [](name); end
  def []=(name, val); end
  def all; end
  def current; end
  def depth; end
  def initialize; end
  def scope; end
end
class SexpInterpreter < SexpProcessor
  def initialize; end
end
class MethodBasedSexpProcessor < SexpProcessor
  def class_stack; end
  def in_klass(name); end
  def in_method(name, file, line, line_max = nil); end
  def in_sklass; end
  def initialize; end
  def klass_name; end
  def method_locations; end
  def method_name; end
  def method_stack; end
  def process_class(exp); end
  def process_defn(exp); end
  def process_defs(exp); end
  def process_module(exp); end
  def process_sclass(exp); end
  def process_until_empty(exp); end
  def sclass; end
  def signature; end
  def with_new_method_stack; end
end
class Object < BasicObject
  def deep_clone; end
end
class SexpProcessorError < StandardError
end
class UnsupportedNodeError < SexpProcessorError
end
class UnknownNodeError < SexpProcessorError
end
class NotEmptyError < SexpProcessorError
end
class SexpTypeError < SexpProcessorError
end
