#!/usr/bin/env ruby

# frozen_string_literal: true

require "irb"
require "irb/completion"

Dir["./day*.rb"].each { |file| require file }

# Config IRB to enable --simple-prompt and auto indent
IRB.conf[:PROMPT_MODE] = :SIMPLE
IRB.conf[:AUTO_INDENT] = true

IRB.start(__FILE__)
