#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "sorbet-runtime"

day = ARGV.first || "day#{Time.now.day}"

require "benchmark"
require "./solution"
require "./#{day}"

benchmark = Benchmark.realtime do
  input = File.readlines("data/#{day}.txt").map(&:chomp)
  solution = Solution.for(day, input)

  puts("Solution for #{day}")
  puts("- Part 1: #{solution.part_one}")
  puts("- Part 2: #{solution.part_two}")
end

puts "Total execution time: #{benchmark.round(3)} seconds"
